feature: add mtls client cert support
openresty/lua-resty-websocket pull request #72
Opened 2022-03-22 09:21 UTC by ADD-SP

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-resty-websocket project.

2022-03-22 09:35 UTC, dndx commented on lib/resty/websocket/client.lua
> +            assert(client_priv_key,
`assert` should be localized at module level.

2022-03-22 09:35 UTC, dndx commented on t/cs.t
> +--- no_check_leak
Is this required?

2022-03-22 09:35 UTC, dndx commented on t/cs.t
> +--- udp_reply eval
Can this be saved as a variable so they the test below can just refer to the function? Like `--- http_config eval: $::HttpConfig`

2022-03-22 11:35 UTC, dndx commented on README.markdown
> +    Specifies a client certificate chain cdata object that will be used while handshaking with remote server.
```suggestion
    Specifies a client certificate chain cdata object that will be used while TLS handshaking with remote server. 
```

2022-03-22 11:35 UTC, dndx commented on lib/resty/websocket/client.lua
> +                return nil, "ssl client cert failed: " .. err
```suggestion
                return nil, "failed to set TLS client certificate: " .. err
```

2022-03-22 12:01 UTC, dndx approved these changes

2022-03-22 12:18 UTC, cppcoffee commented on t/cs.t
> +=== TEST 29: mutual TLS with client certs
Need three newline.

2022-03-22 12:41 UTC, cppcoffee commented on lib/resty/websocket/client.lua
> +    local ssl_verify, server_name, headers, proto_header, origin_header, sock_opts = false
Keep the 80 column limit.

2022-03-23 13:15 UTC, dndx commented
@cppcoffee Could you take another look give a ✅ on this?

2022-03-24 08:34 UTC, zhuizhuhaomeng requested changes

2022-03-24 08:34 UTC, zhuizhuhaomeng commented on t/cs.t
> +    listen 12345 ssl;
Please do not use port 12345. This port is blocked by iptables in other lua-nginx-module.

we can use $TEST_NGINX_RAND_PORT_1, please refer to 
https://github.com/openresty/lua-nginx-module/blob/master/t/139-ssl-cert-by.t#L459

2022-03-24 09:02 UTC, merged

2022-03-24 09:04 UTC, dndx commented
Thank you @zhuizhuhaomeng !